In [ ]:
import numpy as np

In [ ]:
# 모두 0으로 채운 3 x 3 배열 a 생성 
a = np.zeros((3,3))
print(a)
# 모두 1로 채운 2 x 3 배열 b 생성
b = np.ones((2,3))
print(b)
# 5로 채운 2 x 3 x 3 배열 c 생성
c = np.full((2,3,3),5)
print(c)
# 5 x 5 단위 행렬 d 생성
d = np.eye(5)
print(d)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[[5 5 5]
  [5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]
  [5 5 5]]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# range, reshape 함수를 사용하여 1~20 의 정수로 4 x 5 배열 arr 생성
arr = np.arange(1,21).reshape(4,5)
print(arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
# 불린 인덱스를 이용하여 arr 배열의 대각선 '\' 상의 요소 선택
bi = np.eye(4,5, dtype = bool)
print(arr[bi])

[ 1  7 13 19]


In [ ]:
# arr 배열의 인덱스가 짝수인 요소만 조회 (불린 인덱스와 조건식을 조합)
bi = [arr % 2 == 0]
print(arr[tuple(bi)])

[ 2  4  6  8 10 12 14 16 18 20]


# 배열 간 연산

In [ ]:
m1 = np.array([
    [1,2],
    [3,4]
])
m2 = np.array([
    [5,6],
    [7,8]
])

# m1, m2 배열의 각 요소 간 합, 차, 곱 그리고 행렬곱을 구하기
print(m1 + m2)
print(m1 - m2)
print(m1 * m2)
print(np.matmul(m1,m2))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [ ]:
# arr 배열의 컬럼(열)별 합계
print(arr.sum(axis = 0))

[34 38 42 46 50]


In [ ]:
# arr 배열의 행별 평균
print(arr.mean(axis = 1))

[ 3.  8. 13. 18.]


## 구글 드라이브와 연동하여 파일을 불러오기 해 보겠습니다.

In [ ]:
# 아래 코드를 실행하세요

from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


다음과 같은 실행 결과가 나오면 URL을 클릭하세요.

그럼 아래와 같은 페이지가 뜰거에요.

![alt text](https://t1.daumcdn.net/cfile/tistory/99AE13495BECEC180F)


[허용] 버튼을 클릭하시면 인증 코드가 나와요. 코드를 복사하셔서 authorization code: 영역에 붙여 넣기 하시면 됩니다.

이제부터는 /content/gdrive/My Drive/Colab Notebooks/data/ 경로에 업로드한 파일을 colab에서 불러와서 사용할 수 있습니다.

(data 폴더는 따로 만들었어요. 여기에 외부 데이터 파일을 모아 두세요.)




In [ ]:
# 아래 코드를 실행하여 cars 데이터셋을 불러오기 하세요.

dat = np.genfromtxt("/content/gdrive/My Drive/Colab Notebooks/data/cars.txt", skip_header=True)
dat

array([[  4.,   2.],
       [  4.,  10.],
       [  7.,   4.],
       [  7.,  22.],
       [  8.,  16.],
       [  9.,  10.],
       [ 10.,  18.],
       [ 10.,  26.],
       [ 10.,  34.],
       [ 11.,  17.],
       [ 11.,  28.],
       [ 12.,  14.],
       [ 12.,  20.],
       [ 12.,  24.],
       [ 12.,  28.],
       [ 13.,  26.],
       [ 13.,  34.],
       [ 13.,  34.],
       [ 13.,  46.],
       [ 14.,  26.],
       [ 14.,  36.],
       [ 14.,  60.],
       [ 14.,  80.],
       [ 15.,  20.],
       [ 15.,  26.],
       [ 15.,  54.],
       [ 16.,  32.],
       [ 16.,  40.],
       [ 17.,  32.],
       [ 17.,  40.],
       [ 17.,  50.],
       [ 18.,  42.],
       [ 18.,  56.],
       [ 18.,  76.],
       [ 18.,  84.],
       [ 19.,  36.],
       [ 19.,  46.],
       [ 19.,  68.],
       [ 20.,  32.],
       [ 20.,  48.],
       [ 20.,  52.],
       [ 20.,  56.],
       [ 20.,  64.],
       [ 22.,  66.],
       [ 23.,  54.],
       [ 24.,  70.],
       [ 24.,  92.],
       [ 24.,

In [ ]:
# dat 데이터에서 첫번째열은 speed, 두번째열은 dist입니다. speed 데이터만 추출하여 speed 변수에 저장하세요.
speed, dist = np.hsplit(dat,[1])
print(speed)


[[ 4.]
 [ 4.]
 [ 7.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]
 [10.]
 [10.]
 [11.]
 [11.]
 [12.]
 [12.]
 [12.]
 [12.]
 [13.]
 [13.]
 [13.]
 [13.]
 [14.]
 [14.]
 [14.]
 [14.]
 [15.]
 [15.]
 [15.]
 [16.]
 [16.]
 [17.]
 [17.]
 [17.]
 [18.]
 [18.]
 [18.]
 [18.]
 [19.]
 [19.]
 [19.]
 [20.]
 [20.]
 [20.]
 [20.]
 [20.]
 [22.]
 [23.]
 [24.]
 [24.]
 [24.]
 [24.]
 [25.]]


In [ ]:
# speed 의 평균, 분산을 구하세요.
print(np.mean(speed))
print(np.var(speed))

15.4
27.4
